name: Release

on:
  push:
    branches: [ master, alpha, beta ]

jobs:
  release:
    name: Release

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'
          always-auth: true
      - name: Print npm version
        run: npm --version
      # - name: Configure npm
      #   run: |
      #     echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}' > .npmrc
      #     cat .npmrc
      #     cp .npmrc ~/.npmrc
      - name: Install dependencies
        run: npm ci
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Release
        run: npx multi-semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
