name: Release

on:
  push:
    branches: [ master, alpha, beta ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: |
          npm ci
          npm run bootstrap
          npm run build
          npm test

  release:
    name: Release

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'
          scope: typescript-tools
      - name: Compile TypeScript
        run: |
          npm ci
          npm run bootstrap
          npm run build
          npm test
      - name: Release
        run: |
          find . -name 'index.js' | grep @semantic-release/npm/index.js | xargs -I {} npx patch-semantic-release-npm-for-msr --file {}
          npx multi-semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
